markdown: kramdown
permalink: pretty

port: 1337

sass:
  sass_dir: assets/css
  style: :nested

# Site Settings are located in _data > settings.yml

# Site style changes can be made inside _data > styles.yml

# ===============
# Thanks for choosing VARIANT
# ===============
